import { assets } from "../assets/assets";
export const categories = [
  {
    _id: "1",
    name: "Shawarma",
    description: "this is Shawarma",
    image: assets.menu_shawarma_1,
  },
  {
    _id: "2",
    name: "Cake",
    description: "this is cake",
    image: assets.menu_cake_6,
  },
  {
    _id: "3",
    name: "Pizza",
    description: "this is Pizza",
    image: assets.menu_Pizza_1,
  },
  {
    _id: "4",
    name: "Salad",
    description: "this is salad",
    image: assets.menu_salad_3,
  },
  {
    _id: "5",
    name: "Pasta",
    description: "This is Pasta",
    image: assets.menu_pasta_3,
  },
  {
    _id: "6",
    name: "Karahi",
    description: "This is Chicken Karahi",
    image: assets.menu_karahi_3,
  },
  {
    _id: "7",
    name: "Burger",
    description: "This is Burger",
    image: assets.menu_burger_4,
  },
  {
    _id: "8",
    name: "Rolls",
    description: "This is Roles",
    image: assets.menu_Roles_6,
  },
  {
    _id: "8",
    name: "Meat",
    description: "This is Meat",
    image: assets.menu_Meat_1,
  },
];

export const AllFoodsItems = [
  {
    _id: 1,
    name: "Shawarma",
    description: "this is Shawarma with Cheez Flvour",
    category: "Shawarma",
    image: assets.menu_shawarma_1,
    price: 150,
  },
  {
    _id: 2,
    name: "Shawarma",
    description: "Shawarma with Cheez",
    category: "Shawarma",
    image: assets.menu_shawarma_2,
    price: 150,
  },
  {
    _id: 3,
    name: "Shawarma",
    description: "Shawarma with Chatni",
    category: "Shawarma",
    image: assets.menu_shawarma_3,
    price: 150,
  },
  {
    _id: 4,
    name: "Salad",
    description: "Lamon Salad",
    category: "Salad",
    image: assets.menu_salad_1,
    price: 150,
  },
  {
    _id: 5,
    name: "Salad",
    description: "Mix Salad",
    category: "Salad",
    image: assets.menu_salad_2,
    price: 150,
  },
  {
    _id: 6,
    name: "Salad",
    description: "Fruit Salad",
    category: "Salad",
    image: assets.menu_salad_3,
    price: 150,
  },
  {
    _id: 7,
    name: "Salad",
    description: "Veg  Salad",
    category: "Salad",
    image: assets.menu_salad_4,
    price: 150,
  },
  {
    _id: 8,
    name: "Salad",
    description: "Salad",
    category: "Salad",
    image: assets.menu_salad_5,
    price: 150,
  },
  {
    _id: 9,
    name: "Salad",
    description: "Salad",
    category: "Salad",
    image: assets.menu_salad_6,
    price: 150,
  },
  {
    _id: 10,
    name: "Rolls",
    description: "Checken Rolls",
    category: "Rolls",
    image: assets.menu_Roles_1,
    price: 150,
  },
  {
    _id: 11,
    name: "Rolls",
    description: "Cheez Rolls",
    category: "Rolls",
    image: assets.menu_Roles_2,
    price: 150,
  },
  {
    _id: 12,
    name: "Rolls",
    description: "Parata Rolls",
    category: "Rolls",
    image: assets.menu_Roles_3,
    price: 150,
  },
  {
    _id: 13,
    name: "Rolls",
    description: "Samosa Rolls",
    category: "Rolls",
    image: assets.menu_Roles_4,
    price: 150,
  },
  {
    _id: 14,
    name: "Rolls",
    description: "Chicken Rolls with parata",
    category: "Rolls",
    image: assets.menu_Roles_5,
    price: 150,
  },
  {
    _id: 15,
    name: "Rolls",
    description: "Rolls With Salad",
    category: "Rolls",
    image: assets.menu_Roles_6,
    price: 150,
  },
  {
    _id: 16,
    name: "Pizza",
    description: "Cheez medium pizza",
    category: "Pizza",
    image: assets.menu_Pizza_1,
    price: 150,
  },
  {
    _id: 17,
    name: "Pizza",
    description: "Vegs Pizza",
    category: "Pizza",
    image: assets.menu_Pizza_2,
    price: 150,
  },
  {
    _id: 18,
    name: "Pizza",
    description: "Pizza with Coke",
    category: "Pizza",
    image: assets.menu_Pizza_3,
    price: 150,
  },
  {
    _id: 19,
    name: "Pizza",
    description: "Cheez & Veg Pizza",
    category: "Pizza",
    image: assets.menu_Pizza_4,
    price: 150,
  },
  {
    _id: 20,
    name: "Pizza",
    description: "Large Pizza",
    category: "Pizza",
    image: assets.menu_Pizza_5,
    price: 150,
  },
  {
    _id: 21,
    name: "Pasta",
    description: "Large Pasta",
    category: "Pasta",
    image: assets.menu_pasta_1,
    price: 150,
  },
  {
    _id: 22,
    name: "Pasta",
    description: "Vegs Pasta",
    category: "Pasta",
    image: assets.menu_pasta_2,
    price: 150,
  },
  {
    _id: 23,
    name: "Pasta",
    description: "Pasta",
    category: "Pasta",
    image: assets.menu_pasta_3,
    price: 150,
  },
  {
    _id: 24,
    name: "Pasta",
    description: "Small Tomatto Pasta",
    category: "Pasta",
    image: assets.menu_pasta_4,
    price: 150,
  },
  {
    _id: 25,
    name: "Pasta",
    description: "Tomatto Pasta",
    category: "Pasta",
    image: assets.menu_pasta_5,
    price: 150,
  },
  {
    _id: 26,
    name: "Pasta",
    description: "Mint Pasta",
    category: "Pasta",
    image: assets.menu_pasta_6,
    price: 150,
  },
  {
    _id: 27,
    name: "Pasta",
    description: "Chicken Pasta",
    category: "Pasta",
    image: assets.menu_pasta_7,
    price: 150,
  },
  {
    _id: 28,
    name: "Meat",
    description: "Meat with Salad",
    category: "Meat",
    image: assets.menu_Meat_1,
    price: 150,
  },
  {
    _id: 29,
    name: "Meat",
    description: "Beef Meat",
    category: "Meat",
    image: assets.menu_Meat_2,
    price: 150,
  },
  {
    _id: 30,
    name: "Meat",
    description: "Mutton Meat",
    category: "Meat",
    image: assets.menu_Meat_3,
    price: 150,
  },
  {
    _id: 31,
    name: "Karahi",
    description: "Chicken Karahi",
    category: "Karahi",
    image: assets.menu_karahi_1,
    price: 150,
  },
  {
    _id: 32,
    name: "Karahi",
    description: "Lahori Karahi",
    category: "Karahi",
    image: assets.menu_karahi_2,
    price: 150,
  },
  {
    _id: 33,
    name: "Karahi",
    description: "Peshawari Karahi",
    category: "Karahi",
    image: assets.menu_karahi_3,
    price: 150,
  },
  {
    _id: 34,
    name: "Cake",
    description: "chocolate Cake",
    category: "Cake",
    image: assets.menu_cake_1,
    price: 150,
  },
  {
    _id: 35,
    name: "Cake",
    description: "Cream Cake",
    category: "Cake",
    image: assets.menu_cake_2,
    price: 150,
  },
  {
    _id: 36,
    name: "Cake",
    description: "Cake Slice",
    category: "Cake",
    image: assets.menu_cake_3,
    price: 150,
  },
  {
    _id: 37,
    name: "Cake",
    description: "Cream Large Cake",
    category: "Cake",
    image: assets.menu_cake_4,
    price: 150,
  },
  {
    _id: 38,
    name: "Cake",
    description: "Pin Cake",
    category: "Cake",
    image: assets.menu_cake_5,
    price: 150,
  },
  {
    _id: 39,
    name: "Cake",
    description: "3 Layers Chocolate Cake",
    category: "Cake",
    image: assets.menu_cake_6,
    price: 150,
  },
  {
    _id: 40,
    name: "Burger",
    description: "Beef Burger",
    category: "Burger",
    image: assets.menu_burger_1,
    price: 150,
  },
  {
    _id: 41,
    name: "Burger",
    description: "Shami burger",
    category: "Burger",
    image: assets.menu_burger_2,
    price: 150,
  },
  {
    _id: 42,
    name: "Burger",
    description: "Burger with Salad",
    category: "Burger",
    image: assets.menu_burger_3,
    price: 150,
  },
  {
    _id: 43,
    name: "Burger",
    description: "Eggs & Shami Burger",
    category: "Burger",
    image: assets.menu_burger_4,
    price: 150,
  },

];
