import { assets } from "../assets/assets";
export const categories = [
  {
    _id: "1",
    name: "Shorwama",
    description: "this is Shorwama",
    image: assets.menu_img_1,
    price: "50",
  },
  {
    _id: "2",
    name: "Cake",
    description: "this is cake",
    image: assets.menu_img_2,
    price: "50",
  },
  {
    _id: "3",
    name: "Pizza",
    description: "this is Pizza",
    image: assets.menu_img_3,
    price: "50",
  },
  {
    _id: "4",
    name: "Salad",
    description: "this is salad",
    image: assets.menu_img_4,
    price: "50",
  },
  {
    _id: "5",
    name: "Pasta",
    description: "This is Pasta",
    image: assets.menu_img_5,
    price: "50",
  },
  {
    _id: "6",
    name: "Pasha",
    description: "This is Pasha",
    image: assets.menu_img_6,
    price: "50",
  },
  {
    _id: "7",
    name: "Cheez Burger",
    description: "This is Cheez Burger",
    image: assets.menu_img_7,
    price: "50",
  },
  {
    _id: "8",
    name: "Cheez Pizza",
    description: "This is Cheez Pizza",
    image: assets.menu_img_8,
    price: "50",
  },
  {
    _id: "9",
    name: "Burger with Franch Fries",
    description: "This is Burger with Franch Fries",
    image: assets.menu_img_9,
    price: "50",
  },
  {
    _id: "10",
    name: "Burger",
    description: "This is Burger",
    image: assets.menu_img_10,
    price: "50",
  },
];
